version: 2
updates:
  - package-ecosystem: "pip"           
    directory: "/backend"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    commit-message: 
      prefix: "[OPS-001]"

  - package-ecosystem: "docker"
    directories:
      - "/backend"
      - "/frontend"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    commit-message: 
      prefix: "[OPS-001]"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    commit-message: 
      prefix: "[OPS-001]"
