# This compose file is for local development. All secrets are loaded from .env

services:

  backend:
    depends_on:
      - db
    env_file: .env
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
      - db_ver:/app/alembic/versions
    command: ["/bin/sh", "/app/entrypoint.sh"]

  db:
    image: postgres:18-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - db_data_url:/var/lib/postgresql
    ports:
      - "5432:5432"

  frontend:
    env_file: .env
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    command: npm start

volumes:
  db_data_url:
  db_ver: